"""changed cart

Revision ID: 0bed0fdcfaec
Revises: 3d5ebac291fa
Create Date: 2022-12-05 11:09:24.006633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bed0fdcfaec'
down_revision = '3d5ebac291fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('produtc_pic', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('produtc_pic')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
