"""Added users

Revision ID: de49ca40b37b
Revises: e4fca51c7956
Create Date: 2022-12-02 10:35:11.734701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de49ca40b37b'
down_revision = 'e4fca51c7956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=75),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=75),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###
